# Generated by Django 4.2.17 on 2024-12-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('specs', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(blank=True, choices=[('Camera', 'Camera'), ('Accessory', 'Accessory'), ('Film', 'Film')], default='Camera', max_length=50, null=True)),
                ('sub_category', models.CharField(blank=True, choices=[('DSLR', 'DSLR'), ('Point & Shoot', 'Point & Shoot'), ('Mirrorless', 'Mirrorless'), ('Tripod', 'Tripod'), ('Lens', 'Lens'), ('Film Roll', 'Film Roll')], max_length=50, null=True)),
                ('bought_from', models.CharField(blank=True, max_length=255, null=True)),
                ('bought_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
