# Generated by Django 4.2.17 on 2024-12-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cosmetic_condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('average', 'Average'), ('below_average', 'Below Average')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='working_condition',
            field=models.CharField(blank=True, choices=[('fully_working', 'Fully Working'), ('partially_working', 'Partially Working'), ('needs_service', 'Needs Service'), ('non_working', 'Non Working')], max_length=50, null=True),
        ),
    ]
