# Generated by Django 4.2.17 on 2024-12-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_cosmetic_condition_product_working_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.AddField(
            model_name='product',
            name='overall_condition',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
