# Generated by Django 4.2.17 on 2024-12-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_condition_product_overall_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Film Camera', 'Film Camera'), ('Digital Camera', 'Digital Camera'), ('Accessory', 'Accessory'), ('Film', 'Film')], max_length=50, null=True),
        ),
    ]
