# Generated by Django 4.2.17 on 2024-12-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('received', 'received'), ('needs_service', 'Needs Service'), ('sent_for_service', 'Sent For Service')], max_length=50, null=True),
        ),
    ]
