# Generated by Django 4.2.17 on 2024-12-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('received', 'Received'), ('needs_service', 'Needs Service'), ('sent_for_service', 'Sent For Service')], max_length=50, null=True),
        ),
    ]
