# Generated by Django 4.2.17 on 2025-03-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_lot_bought_at_lot_bought_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
