# Generated by Django 4.2.17 on 2025-07-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_lot_status_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('SLR', 'SLR'), ('Point & Shoot', 'Point & Shoot'), ('Mirrorless', 'Mirrorless'), ('Tripod', 'Tripod'), ('Lens', 'Lens'), ('Film Roll', 'Film Roll')], max_length=50, null=True),
        ),
    ]
