# Generated by Django 4.2.17 on 2026-04-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('inventory', '0013_alter_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.organization'),
        ),
    ]
