# Generated by Django 4.2.17 on 2026-04-14 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0014_lot_organization_product_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='funded_by',
            field=models.CharField(choices=[('org', 'Organization'), ('user', 'Team Member')], default='org', max_length=10),
        ),
        migrations.AddField(
            model_name='lot',
            name='funded_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_lots', to=settings.AUTH_USER_MODEL),
        ),
    ]
