# Generated by Django 4.2.17 on 2026-04-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_lot_funded_by_lot_funded_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='listing_status',
            field=models.CharField(blank=True, choices=[('Listed', 'Listed'), ('Unlisted', 'Unlisted'), ('Shipped', 'Shipped')], default='Unlisted', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('SLR Body', 'SLR Body'), ('SLR', 'SLR'), ('Point & Shoot', 'Point & Shoot'), ('Digicam', 'Digicam'), ('Rangefinder', 'Rangefinder'), ('TLR', 'TLR'), ('Mirrorless', 'Mirrorless'), ('DSLR Body', 'DSLR Body'), ('Handycam', 'Handycam'), ('Lens', 'Lens'), ('Lens Adapter', 'Lens Adapter'), ('Tele Converter', 'Tele Converter'), ('Flash', 'Flash'), ('Viewfinder', 'Viewfinder'), ('Shutter Release cable', 'Shutter Release Cable'), ('Expired film', 'Expired Film'), ('Film Roll', 'Film Roll'), ('Tripod', 'Tripod'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
