# Generated by Django 4.2.17 on 2025-07-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_lot_status_payment'),
        ('sales', '0005_alter_sale_shipping_status'),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('servicing', 'Servicing'), ('refund', 'Refund'), ('shipping', 'Shipping'), ('misc', 'Miscellaneous')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='inventory.product')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.DeleteModel(
            name='MiscellaneousExpense',
        ),
        migrations.RemoveField(
            model_name='shippingexpense',
            name='sale',
        ),
        migrations.DeleteModel(
            name='ServicingExpense',
        ),
        migrations.DeleteModel(
            name='ShippingExpense',
        ),
    ]
