# Generated by Django 4.2.17 on 2026-04-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('expense', '0003_make_date_field_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.organization'),
        ),
    ]
