# Generated by Django 4.2.17 on 2024-12-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('shipping_pending', 'Shipping Pending'), ('needs_service', 'Needs Service'), ('sent_for_service', 'Sent For Service')], max_length=128, null=True),
        ),
    ]
