# Generated by Django 4.2.17 on 2024-12-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_shipping_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_status',
        ),
    ]
