# Generated by Django 4.2.17 on 2025-03-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('shipping_pending', 'Shipping Pending'), ('shipping_placed', 'Shipping Placed'), ('shipped', 'Shipped')], max_length=128, null=True),
        ),
    ]
