# Generated by Django 4.2.17 on 2026-01-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_shippinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
