# Generated by Django 4.2.17 on 2026-03-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_add_refund_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='shopify_order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='shopify_order_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
