# Generated by Django 4.2.17 on 2026-04-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_sub_category'),
        ('sales', '0008_sale_shopify_order_id_sale_shopify_order_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='shopify_order_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
