# Generated by Django 4.2.17 on 2026-04-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('sales', '0009_alter_sale_product_alter_sale_shopify_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.organization'),
        ),
    ]
